disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Hayden's Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/logo.png"
  #secondaryLogo = "img/secondary-logo.png"
  description = "A blog for techies"
  #copyright = "Copy, _right?_ :thinking_face:"

[params.homepage]
  title = '$ echo "Hello World!"'
  description = "A blog for techies"
  #image = ""

 [params.author]
  name = "Hayden Plumley"
  email = "mrhaydendp@gmail.com"
  image = "https://avatars.githubusercontent.com/u/29285782?v=4"
  imageQuality = 75
  headline = "A blog for techies"
  bio = "I'm a tech enthusiast who's all about tinkering with electronics, watching horror movies, and making the perfect cup of espresso."
  links = [
     { github = "https://github.com/mrhaydendp" },
     { x-twitter = "https://x.com/mrhaydendp" },
     { link = "https://lynx.mrhaydendp.com/" },
     { email = "mailto:mrhaydendp@gmail.com" },
  ]