media:
  input: assets/images
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
  - name: projects
    label: Projects
    type: collection
    path: content/projects